// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    ChatGpt: typeof import('./src/components/chat-gpt/index.vue')['default']
    CustomDatePicker: typeof import('./src/components/custom-date-picker/index.vue')['default']
    DateTimeRange: typeof import('./src/components/date-time-range/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FeishuUserDialog: typeof import('./src/components/feishu-user-dialog/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FormWraper: typeof import('./src/components/query-form/form-wraper.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    List: typeof import('./src/components/message-box/list.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MessageBox: typeof import('./src/components/message-box/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    QueryForm: typeof import('./src/components/query-form/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default']
    TabItem: typeof import('./src/components/tab-bar/tab-item.vue')['default']
  }
}
